# Generated by Django 5.1.5 on 2025-05-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('branch', models.CharField(default='not given', max_length=50)),
                ('blood_group', models.CharField(default='not given', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('profile_image', models.ImageField(blank=True, default='profile_pics/img_1.png', upload_to='profile_pics/')),
            ],
        ),
    ]
