# Generated by Django 5.1.5 on 2025-05-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='college',
            name='college_code_encrypted',
        ),
        migrations.RemoveField(
            model_name='college',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='college',
            name='status',
        ),
        migrations.AddField(
            model_name='college',
            name='college_code',
            field=models.CharField(default='TEMP123', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='affiliation',
            field=models.CharField(choices=[('Govt', 'Government'), ('Private', 'Private'), ('Autonomous', 'Autonomous')], max_length=20),
        ),
        migrations.AlterField(
            model_name='college',
            name='established_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='college',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
