# Generated by Django 5.1.5 on 2025-05-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_delete_user_remove_college_college_code_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('bus_name', models.CharField(default='Unknown Bus', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('pickup_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='members.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='ClgApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(max_length=15)),
                ('num_departments', models.PositiveIntegerField()),
                ('working_hours', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='college_images/')),
                ('bus_certificate', models.FileField(blank=True, null=True, upload_to='bus_certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='ClgRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(max_length=15)),
                ('num_departments', models.PositiveIntegerField()),
                ('working_hours', models.CharField(max_length=100)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=150, null=True)),
                ('institution_code', models.IntegerField(null=True)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('admission_year', models.IntegerField()),
                ('contact_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('branch', models.CharField(default='not given', max_length=50)),
                ('blood_group', models.CharField(default='not given', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('profile_image', models.ImageField(blank=True, default='profile_pics/img_1.png', upload_to='profile_pics/')),
            ],
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.AddField(
            model_name='busroute',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.clgapproved'),
        ),
    ]
