# Generated by Django 5.1.5 on 2025-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_busroute_busstop_clgapproved_clgrejected_third_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(max_length=15)),
                ('num_departments', models.PositiveIntegerField()),
                ('working_hours', models.CharField(max_length=100)),
                ('bus_certificate', models.FileField(upload_to='bus_certificates/')),
            ],
        ),
    ]
