# Generated by Django 5.1.5 on 2025-05-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='clgapproved',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='clgapproved',
            name='username',
            field=models.CharField(default='username', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='clgrejected',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='clgrejected',
            name='username',
            field=models.CharField(default='username', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='college',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AddField(
            model_name='college',
            name='username',
            field=models.CharField(default='username', max_length=100, unique=True),
        ),
    ]
