# Generated by Django 5.1.5 on 2025-05-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_clgapproved_password_clgapproved_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='college',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='route',
        ),
        migrations.DeleteModel(
            name='Third',
        ),
        migrations.DeleteModel(
            name='BusRoute',
        ),
        migrations.DeleteModel(
            name='BusStop',
        ),
    ]
