# Generated by Django 5.1.5 on 2025-05-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_busroute_college_remove_busstop_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200)),
                ('bus_number', models.CharField(max_length=50)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_contact_number', models.CharField(max_length=15)),
                ('morning_start', models.CharField(max_length=255)),
                ('morning_end', models.CharField(max_length=255)),
                ('morning_fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('morning_time', models.TimeField()),
                ('evening_start', models.CharField(max_length=255)),
                ('evening_end', models.CharField(max_length=255)),
                ('evening_fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evening_time', models.TimeField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_routes', to='members.clgapproved')),
            ],
        ),
    ]
