# Generated by Django 5.1.5 on 2025-05-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_busroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='evening_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='morning_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
