# Generated by Django 5.1.5 on 2025-05-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('course_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_semester', models.CharField(max_length=50)),
                ('admission_number', models.CharField(max_length=20)),
                ('batch_year', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('college_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='clgapproved',
            name='admin_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
