# Generated by Django 5.1.5 on 2025-05-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_student_student_id_student_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedstudent',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='rejectedstudent',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_number',
        ),
    ]
