# Generated by Django 5.1.5 on 2025-05-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_remove_approvedstudent_admission_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectedstudent',
            name='college',
        ),
        migrations.RemoveField(
            model_name='rejectedstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='college',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_ids',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='student001', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='ApprovedStudent',
        ),
        migrations.DeleteModel(
            name='RejectedStudent',
        ),
        migrations.DeleteModel(
            name='StudentRequest',
        ),
    ]
