# Generated by Django 5.1.5 on 2025-05-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='student001', max_length=20, unique=True),
        ),
    ]
