# Generated by Django 5.1.5 on 2025-05-30 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ApprovedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=3)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('course_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_semester', models.CharField(max_length=50)),
                ('batch_year', models.CharField(max_length=20)),
                ('password', models.CharField(default='default_password', max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('approved_on', models.DateTimeField(auto_now_add=True)),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.college')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('course_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_semester', models.CharField(max_length=50)),
                ('batch_year', models.CharField(max_length=20)),
                ('password', models.CharField(default='default_password', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('rejected_on', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField()),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.college')),
            ],
        ),
    ]
