# Generated by Django 5.1.5 on 2025-05-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_student_status_approvedstudent_rejectedstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectedstudent',
            name='college_name',
        ),
        migrations.DeleteModel(
            name='ApprovedStudent',
        ),
        migrations.DeleteModel(
            name='RejectedStudent',
        ),
    ]
