# Generated by Django 5.1.5 on 2025-05-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_remove_rejectedstudent_college_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=3)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='approved_students/')),
                ('course_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_semester', models.CharField(max_length=50)),
                ('batch_year', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Approved', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=3)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='rejected_students/')),
                ('course_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_semester', models.CharField(max_length=50)),
                ('batch_year', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Rejected', max_length=10)),
                ('rejection_reason', models.TextField()),
            ],
        ),
    ]
