# Generated by Django 5.1.5 on 2025-05-31 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_approvedstudent_rejectedstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedstudent',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='rejectedstudent',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='college_name',
        ),
        migrations.AddField(
            model_name='approvedstudent',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='members.clgapproved'),
        ),
        migrations.AddField(
            model_name='rejectedstudent',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='members.clgapproved'),
        ),
    ]
