# Generated by Django 5.1.5 on 2025-05-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_remove_approvedstudent_college_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedstudent',
            name='college',
        ),
        migrations.RemoveField(
            model_name='rejectedstudent',
            name='college',
        ),
        migrations.AddField(
            model_name='approvedstudent',
            name='college_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rejectedstudent',
            name='college_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='college_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
