# Generated by Django 5.1.5 on 2025-06-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_remove_approvedstudent_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedstudent',
            old_name='college_name',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='rejectedstudent',
            old_name='college_name',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='college_name',
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_students', to='members.clgapproved'),
        ),
    ]
