# Generated by Django 5.1.5 on 2025-06-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_rename_college_name_approvedstudent_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedstudent',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
