# Generated by Django 5.1.5 on 2025-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_alter_approvedstudent_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='custom_days_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='payment_methods',
            field=models.TextField(default='[]'),
        ),
    ]
