# Generated by Django 5.1.5 on 2025-06-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_college_custom_days_count_college_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='clgapproved',
            name='custom_days_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clgapproved',
            name='payment_methods',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='clgrejected',
            name='custom_days_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clgrejected',
            name='payment_methods',
            field=models.TextField(default='[]'),
        ),
    ]
