# Generated by Django 5.1.5 on 2025-06-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_paymenttransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
