# Generated by Django 5.1.5 on 2025-06-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_delete_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('netbanking', 'Netbanking'), ('upi', 'UPI'), ('prepaid', 'Prepaid Card'), ('wallet', 'Digital Wallet')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_on_card', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=25, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=15, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
