# Generated by Django 5.1.5 on 2025-06-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'Card'), ('netbanking', 'NetBanking'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('prepaid', 'Prepaid Card')], max_length=20)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry', models.CharField(blank=True, max_length=10, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('prepaid_card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('prepaid_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
