# Generated by Django 5.1.5 on 2025-06-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_payment_delete_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='evening_end',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='evening_fare',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='evening_start',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='evening_time',
        ),
    ]
