# Generated by Django 5.1.5 on 2025-06-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_remove_busroute_evening_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='time_type',
        ),
    ]
