# Generated by Django 5.1.5 on 2025-06-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_remove_stop_time_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='time_type',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening')], default='AM', max_length=2),
        ),
    ]
