# Generated by Django 5.1.5 on 2025-06-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_stop_time_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('semester_bus_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('semester_count', models.IntegerField()),
                ('intake', models.IntegerField()),
                ('department_head', models.CharField(max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.clgapproved')),
            ],
        ),
    ]
