# Generated by Django 5.1.5 on 2025-06-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='intake',
            new_name='number_of_student_in_this_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='semester_bus_fee',
        ),
        migrations.AddField(
            model_name='department',
            name='semester_working_days',
            field=models.IntegerField(default=0),
        ),
    ]
