# Generated by Django 5.1.5 on 2025-06-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_rename_intake_department_number_of_student_in_this_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_logo',
            field=models.ImageField(blank=True, null=True, upload_to='department_logos/'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='members.clgapproved'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('duration', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('DIPLOMA', 'Diploma'), ('PhD', 'Doctorate')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='members.department')),
            ],
        ),
    ]
