# Generated by Django 5.1.5 on 2025-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_department_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_head',
            field=models.CharField(help_text='Name of the tutor/in-charge', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='head_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
