# Generated by Django 5.1.5 on 2025-06-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_course_contact_number_course_course_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_head',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
