# Generated by Django 5.1.5 on 2025-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_alter_course_course_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus_pdf',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.CharField(default='Not updated !'),
        ),
    ]
