# Generated by Django 5.1.5 on 2025-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_course_syllabus_pdf_department_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(default='Not updated !', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='number_of_student_in_this_department',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='semester_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='semester_working_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
