# Generated by Django 5.1.5 on 2025-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_department_notes_alter_department_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(default='Not updated !'),
        ),
        migrations.AlterField(
            model_name='department',
            name='number_of_student_in_this_department',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='semester_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='semester_working_days',
            field=models.IntegerField(default=0),
        ),
    ]
