# Generated by Django 5.1.5 on 2025-06-19 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_alter_department_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedstudent',
            name='assigned_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.busroute'),
        ),
        migrations.AddField(
            model_name='approvedstudent',
            name='assigned_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.stop'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busroute',
            name='filled_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
