# Generated by Django 5.1.5 on 2025-06-19 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_approvedstudent_assigned_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.approvedstudent'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('qr_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.busroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.stop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.approvedstudent')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.ticket'),
        ),
    ]
