# Generated by Django 5.1.5 on 2025-06-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_payment_student_payment_total_fare_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedstudent',
            name='status',
            field=models.CharField(default='Denied', max_length=10),
        ),
    ]
