# Generated by Django 5.1.5 on 2025-06-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_alter_approvedstudent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
    ]
