# Generated by Django 5.2.5 on 2025-12-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(default='Not updated !', max_length=20),
        ),
    ]
