# Generated by Django 5.0.4 on 2026-05-09 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_alter_department_department_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedstudent',
            name='assigned_route',
        ),
        migrations.RemoveField(
            model_name='approvedstudent',
            name='assigned_stop',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.student'),
        ),
        migrations.DeleteModel(
            name='RejectedStudent',
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.busroute'),
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.stop'),
        ),
        migrations.AddField(
            model_name='student',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='members.clgapproved'),
        ),
        migrations.DeleteModel(
            name='ApprovedStudent',
        ),
    ]
